CREATE TABLE IF NOT EXISTS `sensitive_word` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  word VARCHAR(64) NOT NULL,
  category VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
